FROM php:8.2-apache

# Enable required PHP extensions for MySQL and basic app compatibility.
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Ensure only one Apache MPM is active (required by mod_php).
RUN a2dismod mpm_event mpm_worker || true \
    && a2enmod mpm_prefork rewrite \
    && sed -ri 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf

WORKDIR /var/www/html
COPY . /var/www/html
COPY docker/start.sh /usr/local/bin/start.sh

# Ensure runtime write permissions for logs/sessions generated by the app.
RUN chown -R www-data:www-data /var/www/html

RUN chmod +x /usr/local/bin/start.sh

EXPOSE 80

CMD ["/usr/local/bin/start.sh"]
