FROM php:8.2-apache

# Enable required PHP extensions for MySQL and basic app compatibility.
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Enable Apache rewrite and allow .htaccess rules.
RUN a2enmod rewrite \
    && sed -ri 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf

WORKDIR /var/www/html
COPY . /var/www/html

# Ensure runtime write permissions for logs/sessions generated by the app.
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
